language: php

php:
  - 5.6
  - 7.0
  - hhvm

before_script:
  - "composer self-update"
  - "composer --version"
  - "composer install --no-dev --no-interaction --prefer-dist"

script:
  - "phpunit -c phpunit.xml.dist"
